= Ronak Lakhotia - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Weaver
Weaver is a desktop address book application meant for NUS students. Weaver helps students maintain their day to day timetable and schedule their daily reminders.
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC. Some of the tools used for this project are
Github, Intellij, SceneBuilder and JAVAFX.

*Code contributed*: [https://github.com/CS2103AUG2017-W13-B2/main/blob/master/collated/main/RonakLakhotia.md[Functional code]] [https://github.com/CS2103AUG2017-W13-B2/main/blob/master/collated/test/RonakLakhotia.md[Test code]] {give links to collated code files}

=== Enhancement Added: Facebook Integration

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=facebook]

#End of Extract#

---

==== Justification

This implementation is very useful for users as they can connect with their friends and family through
Weaver, thereby saving them the trouble of opening a browser on their desktop. It also promotes a healthy social media life. +
The command format is easy to follow. Opening the facebook page on the browser panel is more convenient than
searching for the person manually on the default browser.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=facebook]

#End of Extract#

---

=== Enhancement Added: Add command `photo`

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=addphoto]

#End of Extract#

---
==== Justification

Allows user to choose any image in their local device and use Command Line Interface to specify the path of the image. +
This way the user can display the pictures on their contact lists. Users can also identify people more easily if two or+
more people have the same name. It also hads a visual appeal to the Application.+

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=addphoto]

#End of Extract#

---

=== Enhancement Added: Add command `email`

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=email]

#End of Extract#

---

=== Other contributions

* Set up a reminders panel (Pull requests https://github.com[#33], https://github.com[#34])
* Wrote additional tests to increase coverage (Pull requests https://github.com[#36], https://github.com[#38])


